# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shablon.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.setWindowModality(QtCore.Qt.NonModal)
        MainForm.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainForm.setAutoFillBackground(False)
        MainForm.setStyleSheet("/* ЦИФРЫ */\n"
"#btn0,#btn1,#btn2,#btn3,#btn4,#btn5,#btn6,#btn7,#btn8,#btn9 \n"
"{\n"
"    background-color: white; \n"
"    border: none\n"
"}\n"
"#btn0:hover,#btn1:hover,#btn2:hover,#btn3:hover,#btn4:hover,#btn5:hover,#btn6:hover,#btn7:hover,#btn8:hover,#btn9:hover{\n"
"    background-color: rgb(116, 116, 116); \n"
"    border: 1px solid rgb(54, 54, 54)\n"
"}\n"
"#btn0:pressed,#btn1:pressed,#btn2:pressed,#btn3:pressed,#btn4:pressed,#btn5:pressed,#btn6:pressed,#btn7:pressed,#btn8:pressed,#btn9:pressed{\n"
"    background-color: rgb(136, 136, 136);\n"
"}\n"
"/* КНОПКИ УПРАВЛЕНЯ */\n"
"#btnac,#btnleft,#btnright,#btnstepen,#btnumnoz, #btndot,#btnequally,#btnplus,#btnminus,#btndelit  {\n"
"    background-color: rgb(213, 213, 213);\n"
"    border: none;\n"
"}\n"
"\n"
"#btnac:hover,#btnleft:hover,#btnright:hover,#btnstepen:hover,#btnumnoz:hover,#btndot:hover,#btnequally:hover,#btnplus:hover,#btnminus:hover,#btndelit:hover {\n"
"    background: rgb(150, 150, 150);\n"
"    border: 1px solid rgb(100, 100, 100)\n"
"} \n"
"\n"
"#btnac:pressed,#btnleft:pressed,#btnright:pressed,#btnstepen:pressed,#btnumnoz:pressed,#btndot:pressed,#btnequally:pressed,#btnplus:pressed,#btnminus:pressed,#btndelit:pressed {\n"
"    background:rgb(180, 180, 180)\n"
"} ")
        self.out_label = QtWidgets.QLabel(MainForm)
        self.out_label.setGeometry(QtCore.QRect(0, 20, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.out_label.setFont(font)
        self.out_label.setStyleSheet("margin: 0; border: none; padding: 10")
        self.out_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.out_label.setObjectName("out_label")
        self.btn7 = QtWidgets.QPushButton(MainForm)
        self.btn7.setGeometry(QtCore.QRect(0, 190, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(MainForm)
        self.btn8.setGeometry(QtCore.QRect(70, 190, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(MainForm)
        self.btn9.setGeometry(QtCore.QRect(140, 190, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.btn4 = QtWidgets.QPushButton(MainForm)
        self.btn4.setGeometry(QtCore.QRect(0, 250, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.btn6 = QtWidgets.QPushButton(MainForm)
        self.btn6.setGeometry(QtCore.QRect(140, 250, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.btn5 = QtWidgets.QPushButton(MainForm)
        self.btn5.setGeometry(QtCore.QRect(70, 250, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.btn1 = QtWidgets.QPushButton(MainForm)
        self.btn1.setGeometry(QtCore.QRect(0, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.btn3 = QtWidgets.QPushButton(MainForm)
        self.btn3.setGeometry(QtCore.QRect(140, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(MainForm)
        self.btn2.setGeometry(QtCore.QRect(70, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.btndot = QtWidgets.QPushButton(MainForm)
        self.btndot.setGeometry(QtCore.QRect(0, 370, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btndot.setFont(font)
        self.btndot.setStyleSheet("")
        self.btndot.setObjectName("btndot")
        self.btn0 = QtWidgets.QPushButton(MainForm)
        self.btn0.setGeometry(QtCore.QRect(70, 370, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("")
        self.btn0.setObjectName("btn0")
        self.btnequally = QtWidgets.QPushButton(MainForm)
        self.btnequally.setGeometry(QtCore.QRect(140, 370, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnequally.setFont(font)
        self.btnequally.setStyleSheet("")
        self.btnequally.setObjectName("btnequally")
        self.btnplus = QtWidgets.QPushButton(MainForm)
        self.btnplus.setGeometry(QtCore.QRect(220, 190, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnplus.setFont(font)
        self.btnplus.setStyleSheet("")
        self.btnplus.setObjectName("btnplus")
        self.btnminus = QtWidgets.QPushButton(MainForm)
        self.btnminus.setGeometry(QtCore.QRect(220, 250, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnminus.setFont(font)
        self.btnminus.setStyleSheet("")
        self.btnminus.setObjectName("btnminus")
        self.btndelit = QtWidgets.QPushButton(MainForm)
        self.btndelit.setGeometry(QtCore.QRect(220, 310, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btndelit.setFont(font)
        self.btndelit.setStyleSheet("")
        self.btndelit.setObjectName("btndelit")
        self.btnumnoz = QtWidgets.QPushButton(MainForm)
        self.btnumnoz.setGeometry(QtCore.QRect(220, 370, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnumnoz.setFont(font)
        self.btnumnoz.setObjectName("btnumnoz")
        self.btnleft = QtWidgets.QPushButton(MainForm)
        self.btnleft.setGeometry(QtCore.QRect(0, 130, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnleft.setFont(font)
        self.btnleft.setObjectName("btnleft")
        self.btnright = QtWidgets.QPushButton(MainForm)
        self.btnright.setGeometry(QtCore.QRect(70, 130, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnright.setFont(font)
        self.btnright.setObjectName("btnright")
        self.btnstepen = QtWidgets.QPushButton(MainForm)
        self.btnstepen.setGeometry(QtCore.QRect(140, 130, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnstepen.setFont(font)
        self.btnstepen.setObjectName("btnstepen")
        self.btnac = QtWidgets.QPushButton(MainForm)
        self.btnac.setGeometry(QtCore.QRect(220, 130, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnac.setFont(font)
        self.btnac.setStyleSheet("")
        self.btnac.setObjectName("btnac")

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Калькулятор"))
        MainForm.setWindowIcon(QIcon('icon.png')) 
        self.out_label.setText(_translate("MainForm", "0"))
        self.btn7.setText(_translate("MainForm", "7"))
        self.btn8.setText(_translate("MainForm", "8"))
        self.btn9.setText(_translate("MainForm", "9"))
        self.btn4.setText(_translate("MainForm", "4"))
        self.btn6.setText(_translate("MainForm", "6"))
        self.btn5.setText(_translate("MainForm", "5"))
        self.btn1.setText(_translate("MainForm", "1"))
        self.btn3.setText(_translate("MainForm", "3"))
        self.btn2.setText(_translate("MainForm", "2"))
        self.btndot.setText(_translate("MainForm", "."))
        self.btn0.setText(_translate("MainForm", "0"))
        self.btnequally.setText(_translate("MainForm", "="))
        self.btnplus.setText(_translate("MainForm", "+"))
        self.btnminus.setText(_translate("MainForm", "-"))
        self.btndelit.setText(_translate("MainForm", "/"))
        self.btnumnoz.setText(_translate("MainForm", "×"))
        self.btnleft.setText(_translate("MainForm", "("))
        self.btnright.setText(_translate("MainForm", ")"))
        self.btnstepen.setText(_translate("MainForm", "^"))
        self.btnac.setText(_translate("MainForm", "AC"))
